# Generated by Django 4.2.4 on 2023-09-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEtudiant', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('origineScolaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMatiere', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('objectif', models.CharField(max_length=100)),
                ('idEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libexamen.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProgramme', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('annee', models.CharField(max_length=100)),
                ('idEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libexamen.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProjet', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('idEtudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libexamen.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProgrammeMatiere', models.CharField(max_length=100, unique=True)),
                ('idMatiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libexamen.matiere')),
                ('idProgramme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libexamen.programme')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='idProjet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libexamen.projet'),
        ),
    ]
